services:
  redis:
    image: redis:${REDIS_VERSION:-latest}
    container_name: opentranslive-redis

  mongodb:
    image: mongo:${MONGODB_VERSION:-latest}
    container_name: opentranslive-db
    ports:
      - "127.0.0.1:${MONGO_PORT:-27017}:27017"
    volumes:
      - ./mongo_data:/data/db

  backend:
    build: .
    container_name: opentranslive-app
    ports:
      - "127.0.0.1:${SERVER_PORT:-5000}:5000"
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    command: ["./.venv/bin/uvicorn", "app:socket_app", "--host", "0.0.0.0", "--port", "5000", "--workers", "${SERVER_WORKERS:-1}", "--ws", "websockets", "--reload"]
    depends_on:
      - redis
      - mongodb

